<?php
// Set the content type header for JSON response
header('Content-Type: application/json');

// 1. Include the external configuration file
// NOTE: Ensure 'email-config.php' is in the same directory as this file.
require_once 'email-config.php'; 

// --- Configuration ---
// Now using constants defined in email-config.php:
$DEFAULT_RECIPIENT = SYSTEM_RECIPIENT_EMAIL; 
$SENDER_EMAIL = SYSTEM_SENDER_EMAIL; 
// -----------------------

// --- Utility function to format the weather report into an HTML list ---
function formatReportHtml($report, $title, $backgroundColor = '#f0f4f8') {
    $list_items = '';
    
    // Create an HTML list of metrics
    foreach ($report as $label => $value) {
        if ($value !== '--' && $label !== 'Total Rainfall') { // Exclude Total Rainfall as it's typically tracked elsewhere
             // Basic inline styling for a clean look
             $list_items .= '
             <tr>
                 <td style="padding: 8px 15px; border-bottom: 1px solid #e0e0e0; font-weight: bold; color: #333;">' . htmlspecialchars($label) . '</td>
                 <td style="padding: 8px 15px; border-bottom: 1px solid #e0e0e0; color: #007bff; text-align: right;">' . htmlspecialchars($value) . '</td>
             </tr>';
        }
    }
    
    // Wrap the content in a responsive, modern HTML template with inline CSS
    $html_body = '
    <div style="font-family: Arial, sans-serif; line-height: 1.6; background-color: ' . $backgroundColor . '; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background: #ffffff; padding: 20px; border-radius: 10px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
            
            <h2 style="color: #005a9c; border-bottom: 2px solid #005a9c; padding-bottom: 10px; margin-top: 0;">
                ' . htmlspecialchars($title) . '
            </h2>
            
            <table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-top: 20px; border-collapse: collapse;">
                ' . $list_items . '
            </table>

            <p style="margin-top: 30px; font-size: 12px; color: #888;">
                This report was generated by the automated Los Ebanos Dashboard Scheduler.
            </p>
        </div>
    </div>';

    return $html_body;
}

// --- Security Check ---
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['status' => 'error', 'message' => 'Method not allowed.']);
    exit;
}

// --- Data Processing ---
$json_data = file_get_contents('php://input');
$data = json_decode($json_data, true);

// Extract required data
$event_type = $data['event_type'] ?? 'UNKNOWN'; 
$weather_report_data = $data['weather_report'] ?? [];
$to = $data['recipient'] ?? $DEFAULT_RECIPIENT; // Use the centralized default recipient

// Prepare HTML headers for the email
$headers = "From: Los Ebanos Dashboard <" . $SENDER_EMAIL . ">\r\n"; // Use the centralized sender email
$headers .= "MIME-Version: 1.0\r\n";
// *** CRITICAL CHANGE: Set Content-Type to HTML ***
$headers .= "Content-Type: text/html; charset=UTF-8\r\n";

$message = '';
$subject = '';

// --- Logic Branching based on Event Type ---

if ($event_type === 'SPRINKLER_ACTIVATION') {
    $rainfall = $data['rainfall'] ?? 'N/A';
    $threshold = $data['threshold'] ?? 'N/A';

    $subject = "🚨 IRRIGATION ACTIVATION ALERT: Rain Below Threshold!";
    
    // Create a custom title/summary for the activation email
    $alert_title = "Sprinkler System Activated at " . date('g:i A T');
    $alert_summary = '<p style="color: #cc0000; font-size: 16px; font-weight: bold;">Rainfall (' . htmlspecialchars($rainfall) . ' in.) is below the threshold (' . htmlspecialchars($threshold) . ' in.). Irrigation initiated.</p>';
    
    // Add activation summary to the HTML body
    $message = formatReportHtml($weather_report_data, $alert_title, '#fff0f0'); // Use a light red background for alerts
    $message = str_replace('<h2', $alert_summary . '<h2', $message);
    

} elseif ($event_type === 'WEATHER_REPORT') {
    // Logic for the dashboard scheduler (index.html)
    $subject = "Current Weather Report: " . date('g:i A T');
    
    $title = "Los Ebanos 30-Minute Weather Snapshot";
    
    // Generate the standard weather report HTML
    $message = formatReportHtml($weather_report_data, $title);

} else {
    // Handle unknown or missing event type (still sending a basic email for logging)
    $subject = "Unknown Dashboard Event Alert";
    $message = "Unknown event type received. Event: " . htmlspecialchars($event_type);
    $message = formatReportHtml([], $subject); // Send an empty report with the subject as the title
}


// --- Send Email ---
if (mail($to, $subject, $message, $headers)) {
    echo json_encode(['status' => 'success', 'message' => 'HTML Email notification sent successfully for event type: ' . $event_type]);
} else {
    http_response_code(500);
    echo json_encode(['status' => 'error', 'message' => 'Failed to send email via server mail function. Check PHP mail configuration.']);
}

?>
